package models;

public enum Operations {
    // Config Service
    CONFIG_REQUEST,
    SET_CONFIG_REQUEST,

    // Registry Service
    NEW_USER_REQUEST,
    AUTHENTICATION_REQUEST,
    AUTHORIZATION_REQUEST,
    LOGOUT_REQUEST,
    DELETE_USER_REQUEST,

    // Data Service
    SUBMIT_USER_DATALOG,
    GET_USER_DATALOGS,
    START_SHIFT_REQUEST,
    END_SHIFT_REQUEST,
    GET_USER_SHIFTLOGS,

    // Profiler Service
    REGISTER_PROFILE,
    SET_USER_PROFILE,
    GET_PROFILES
}